### ISSUE TITLE
Serilog's Application Insight sink does not put the right Severity Level on Azure Application Insights when logging errors or warnings

### ISSUE THREAD

**Issue by Arash-Sabet** [serilog-contrib/serilog-sinks-applicationinsights#197] opened 2022-06-16 19:06 UTC
**Description**
We have a .NET 6.0 Azure Function App (dotnet-isolated) whose Serilog's configuration is per the following entry in the appsettings.json file:

```json
"Serilog": {
		"Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.ApplicationInsights" ],
		"WriteTo": [
			{
				"Name": "Console",
				"Args": {
					"theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
					"outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}",
					"restrictedToMinimumLevel": "Information"
				}
			},
			{
				"Name": "ApplicationInsights",
				"Args": {
					"instrumentationKey": "MASKED-KEY",
					"telemetryConverter": MyTelemetryConverter, My",
					"restrictedToMinimumLevel": "Information"
				}
			}
		],
		"Enrich": [ "FromLogContext" ],
		"MinimumLevel": {
			"Default": "Information",
			"Override": {
				"Microsoft": "Information",
				"System": "Information"
			}
		}
	}
```
The following C# extension method reads this configuration entry in the function app's Program.cs file at the startup time:

```cs
	public static IHostBuilder UseLogger(this IHostBuilder hostBuilder)
	{
		hostBuilder.ConfigureLogging(loggingBuilder => loggingBuilder.Services.AddSingleton<ILoggerProvider, DefaultLoggerProvider>());
		hostBuilder.UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration.ReadFrom.Configuration(hostingContext.Configuration));
		return hostBuilder;
	}
```
`ILogger` interface is perfectly available all across the application, and we can log different messages to the AI, for example:

```cs
_logger.LogError("My fictitious error message here");
```
The error message is logged, but its severity level is registered as "Information" instead of "Error". This issue applies to warnings too.

This is how the log appears on the AI:
![image](https://user-images.githubusercontent.com/26050123/174143945-5ef1e70a-1cbe-498e-992d-0b069f352cca.png)

The **[6:25:36 ERR]** text in the screenshot above proves that the message was logged as an error per the formatting configuration found in the appsettings.json file. Also please note that the `MyTelemetryConverter` implementation does not interfere with log levels at all.

*Note: Logging exceptions works fine.*

**Reproduction**
Please see above.

**Expected behavior**
Errors and warning messages should have Error and Warning levels.

**Relevant package, tooling, and runtime versions**
dotnet environment:

> .NET SDK (reflecting any global.json):
>  Version:   6.0.301
>  Commit:    43f9b18481
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22000
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.301\
> 
> Host (useful for support):
>   Version: 6.0.6
>   Commit:  7cca709db2
> 
> .NET SDKs installed:
>   3.1.416 [C:\Program Files\dotnet\sdk]
>   6.0.201 [C:\Program Files\dotnet\sdk]
>   6.0.301 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

.NET project's configuration:

```xml
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplictUsings>enable</ImplictUsings>
		<Nullable>enable</Nullable>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

<ItemGroup>
<PackageReference Include="Serilog" Version="2.11.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="4.2.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="3.1.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
		<PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.1.1-dev-00170" />
		<PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
</ItemGroup>
```
**Additional context**
n/a

**Comment by nblumhardt** [comment] 2022-06-17 03:05
Duplicate of https://stackoverflow.com/questions/72650961/serilogs-application-insight-sink-does-not-put-the-right-severity-level-on-azur

**Closed by nblumhardt** 2022-06-17 03:05 UTC
Labels: bug

**Comment by Arash-Sabet** [comment] 2022-06-17 11:59
@nblumhardt This ticket should have stayed open. The answer given in the Stackoverflow post was not specific nor the possible feature in the sink is documented.
