### ISSUE TITLE
.NET Core and TelemetryConfiguration.Active is deprecated

### ISSUE THREAD

**Issue by ravensorb** [serilog-contrib/serilog-sinks-applicationinsights#141] opened 2020-08-13 14:52 UTC
Given that is TelemetryConfiguration.Active [deprecated](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1152) is there a new recommended approach to integrating Serilog with AppInsights in .netcore in general and azure functions specifically?

**Comment by JakeAlmer** [comment] 2020-08-28 01:01
duplicate of https://github.com/serilog/serilog-sinks-applicationinsights/issues/121

**Comment by dglozano** [comment] 2021-04-10 14:45
Have created a PR #160  to update the README with further instructions. You can [take a look here](https://github.com/serilog/serilog-sinks-applicationinsights/pull/160/files).

**Comment by raigol** [comment] 2021-05-21 08:49
> Have created a PR #160 to update the README with further instructions. You can [take a look here](https://github.com/serilog/serilog-sinks-applicationinsights/pull/160/files).

I tried the solution from  PR #160 but it gives 
"The logger is already frozen." Source "Serilog.Extensions.Hosting" 
any suggestions?

**Comment by dglozano** [comment] 2021-05-21 08:52
@raigol could you post a code snippet?

**Comment by raigol** [comment] 2021-05-21 09:08
`        public static int Main(string[] args)
        {            
            Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .CreateBootstrapLogger();

            try
            {
                CreateWebHostBuilder(args).Build().Run();
                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Orders API terminated unexpectedly");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }`


`        public static IHostBuilder CreateWebHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((context, services, loggerConfiguration) =>
                loggerConfiguration
                .WriteTo.ApplicationInsights(services.GetRequiredService<TelemetryConfiguration>(), TelemetryConverter.Traces))
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).ConfigureAppConfiguration((context, builder) =>
                {
                    builder.AddJsonFile("azurekeyvault.json", true, true);
                    var root = builder.Build();
                    builder.AddAzureKeyVault(
                        root["KeyVault--Url"],
                        root["KeyVault--ClientId"],
                        root["KeyVault--ClientSecret"]
                    );

                    var isDevelopment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == Environments.Development;
                    if (isDevelopment)
                    {
                        builder.AddUserSecrets<Startup>();
                    }
                });`

**Comment by Kira-Lappo** [comment] 2021-09-08 09:54
@raigol what version of seriog packages do you use? yesterday I installed the latest one and I could not use  this initialization anymore.

```csharp
.UseSerilog((context, services, loggerConfiguration) => { /*.code here...*/})
````

**Comment by nblumhardt** [comment] 2022-05-02 00:08
The README now shows how to avoid `TelemetryConfiguration.Active`, so I'll close this, but please see also #156 for some continuing discussions. Thanks!

**Closed by nblumhardt** 2022-05-02 00:08 UTC

**Comment by dominik-weber** [comment] 2022-05-02 00:41
@Kira-Lappo i'm late to the party but discovered the same issue a while back. For some reason, the overload for `UseSerilog` that exposes the service provider is only available for the `IHostBuilder`, **NOT** the `IWebHostBuilder` interface. You'll need to migrate your project to use IHostBuilder instead. The good news is that this migration should be quite painless, at least it was for me. IHostBuilder afaik was introduced with .NET Core 3, here's the migration notes: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#hostbuilder-replaces-webhostbuilder

if you're interested, i have posted my code in the discussion of ticket #156
